import type { Metadata } from "next";
import { updateAlertRule } from "@/app/admin/actions";
import { AdminHeader, AdminPanel, AdminTable, EmptyAdminState, StatusBadge, formatDate } from "@/components/admin/admin-ui";
import { requireAdmin } from "@/lib/admin/auth";
import { getAdminSettings } from "@/lib/admin/data";
import { recordAdminAudit } from "@/lib/telemetry/server";
import styles from "../admin.module.css";

export const metadata: Metadata = { title: "Settings" };

export default async function AdminSettingsPage() {
  const admin = await requireAdmin(); const { rules, incidents } = await getAdminSettings();
  await recordAdminAudit({ adminUserId: admin.id, action: "admin_page_viewed", targetType: "page", targetId: "settings" });
  return <><AdminHeader eyebrow="Controls" title="Observability settings" description="Alert thresholds, enabled status, open incidents, retention guidance, and integration readiness." /><AdminPanel title="Alert rules" description="Rules are stored now; scheduled evaluation and external notification delivery are deployment follow-ups."><div className={styles.ruleGrid}>{rules.map((rule) => <article className={styles.rule} key={rule.id}><div><h3>{rule.name}</h3><p>{rule.metric} · {rule.comparison} threshold · {rule.window_minutes} minute window · <StatusBadge value={rule.severity} /></p></div><form action={updateAlertRule}><input type="hidden" name="id" value={rule.id} /><label>Threshold<input type="number" name="threshold" step="0.01" min="0" defaultValue={rule.threshold} /></label><label>Enabled<input type="checkbox" name="enabled" value="true" defaultChecked={rule.enabled} /></label><button type="submit">Save</button></form></article>)}</div></AdminPanel><AdminPanel title="Alert incidents">{incidents.length ? <AdminTable><thead><tr><th>Created</th><th>Status</th><th>Rule</th><th>Observed</th><th>Message</th><th>Resolved</th></tr></thead><tbody>{incidents.map((incident) => <tr key={incident.id}><td>{formatDate(incident.created_at)}</td><td><StatusBadge value={incident.status} /></td><td>{incident.rule_id || "Deleted rule"}</td><td>{incident.observed_value ?? "—"}</td><td>{incident.message}</td><td>{formatDate(incident.resolved_at)}</td></tr>)}</tbody></AdminTable> : <EmptyAdminState title="No alert incidents" description="No threshold evaluation has opened an incident." />}</AdminPanel><AdminPanel title="Deployment integrations"><div className={styles.ruleGrid}><article className={styles.rule}><div><h3>Render</h3><p>Use `/api/health` for platform health checks. Connect Render log drains or OpenTelemetry when the account tier supports them.</p></div><StatusBadge value="ready" /></article><article className={styles.rule}><div><h3>External alerts</h3><p>Connect scheduled rule evaluation to Slack, PagerDuty, or email. No webhook URL or secret belongs in this table.</p></div><StatusBadge value="prepared" /></article><article className={styles.rule}><div><h3>Retention</h3><p>Recommended defaults: 90 days for detailed client/API events, 180 days for operational errors, and 7 years for admin audit and financial events where policy requires.</p></div><StatusBadge value="documented" /></article></div></AdminPanel></>;
}