import type { Metadata } from "next";
import { AdminHeader, AdminPanel, AdminTable, EmptyAdminState, MetricCard, RangeLinks, StatusBadge, formatDate, formatDuration, formatNumber } from "@/components/admin/admin-ui";
import { requireAdmin } from "@/lib/admin/auth";
import { adminDateRange, getAdminAi } from "@/lib/admin/data";
import { recordAdminAudit } from "@/lib/telemetry/server";
import styles from "../admin.module.css";

export const metadata: Metadata = { title: "AI and search" };

export default async function AdminAiPage({ searchParams }: { searchParams: Promise<{ days?: string }> }) {
  const admin = await requireAdmin(); const { days } = adminDateRange((await searchParams).days); const { ai, searches } = await getAdminAi(days);
  await recordAdminAudit({ adminUserId: admin.id, action: "admin_page_viewed", targetType: "page", targetId: "ai", metadata: { days } });
  const completed = ai.filter((row) => row.status === "completed"); const failed = ai.filter((row) => row.status === "failed"); const totalCost = completed.reduce((sum, row) => sum + Number(row.estimated_cost_usd || 0), 0); const tokens = completed.reduce((sum, row) => sum + Number(row.total_tokens || 0), 0); const latency = completed.length ? completed.reduce((sum, row) => sum + Number(row.latency_ms || 0), 0) / completed.length : 0; const searchSuccess = searches.filter((row) => row.status === "completed").length;
  return <><AdminHeader eyebrow="AI operations" title="OpenAI and web search" description="Cost, tokens, latency, retries, parse failures, timeouts, evidence-source volume, and failure modes."><RangeLinks current={days} /></AdminHeader><div className={styles.metricGrid}><MetricCard label="AI requests" value={ai.length} /><MetricCard label="AI success" value={`${ai.length ? Math.round(completed.length / Math.max(1, completed.length + failed.length) * 100) : 0}%`} tone={failed.length ? "warning" : "good"} /><MetricCard label="AI cost" value={`$${totalCost.toFixed(2)}`} /><MetricCard label="Tokens" value={formatNumber(tokens)} /><MetricCard label="AI latency" value={formatDuration(latency)} /><MetricCard label="Search success" value={`${searches.length ? Math.round(searchSuccess / searches.length * 100) : 0}%`} /></div><AdminPanel title="AI requests">{ai.length ? <AdminTable><thead><tr><th>Time</th><th>Status</th><th>Model/stage</th><th>Latency</th><th>Tokens</th><th>Cost</th><th>Retries</th><th>Diagnostics</th></tr></thead><tbody>{ai.map((row) => <tr key={row.id}><td>{formatDate(row.created_at)}</td><td><StatusBadge value={row.status} /></td><td>{row.model}<br /><small>{row.stage}</small></td><td>{formatDuration(row.latency_ms)}</td><td>{formatNumber(row.total_tokens)}</td><td>${Number(row.estimated_cost_usd || 0).toFixed(4)}</td><td>{row.retry_count}</td><td>{row.json_parse_failure ? "JSON parse" : row.timed_out ? "Timeout" : row.refusal ? "Refusal" : row.error_code || "—"}</td></tr>)}</tbody></AdminTable> : <EmptyAdminState />}</AdminPanel><AdminPanel title="Web search"><AdminTable><thead><tr><th>Time</th><th>Status</th><th>Queries</th><th>Sources</th><th>Citations</th><th>Latency</th><th>Failure</th></tr></thead><tbody>{searches.map((row) => <tr key={row.id}><td>{formatDate(row.created_at)}</td><td><StatusBadge value={row.status} /></td><td>{row.query_count}</td><td>{row.source_count}</td><td>{row.citation_count}</td><td>{formatDuration(row.latency_ms)}</td><td>{row.failure_reason || "—"}</td></tr>)}</tbody></AdminTable></AdminPanel></>;
}