import type { Metadata } from "next";
import { AdminHeader, AdminPanel, AdminTable, EmptyAdminState, MetricCard, RangeLinks, StatusBadge, formatDate, formatDuration } from "@/components/admin/admin-ui";
import { requireAdmin } from "@/lib/admin/auth";
import { adminDateRange, getAdminPerformance } from "@/lib/admin/data";
import { recordAdminAudit } from "@/lib/telemetry/server";
import styles from "../admin.module.css";

export const metadata: Metadata = { title: "Performance" };

export default async function AdminPerformancePage({ searchParams }: { searchParams: Promise<{ days?: string }> }) {
  const admin = await requireAdmin(); const { days } = adminDateRange((await searchParams).days); const { api, web } = await getAdminPerformance(days);
  await recordAdminAudit({ adminUserId: admin.id, action: "admin_page_viewed", targetType: "page", targetId: "performance", metadata: { days } });
  const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0; const apiLatency = average(api.map((row) => Number(row.latency_ms))); const failures = api.filter((row) => !row.success).length; const poorWeb = web.filter((row) => row.rating === "poor").length; const endpoints = Object.values(api.reduce<Record<string, { endpoint: string; count: number; failures: number; total: number; max: number }>>((totals, row) => { const item = totals[row.endpoint] || { endpoint: row.endpoint, count: 0, failures: 0, total: 0, max: 0 }; item.count += 1; item.failures += row.success ? 0 : 1; item.total += Number(row.latency_ms); item.max = Math.max(item.max, Number(row.latency_ms)); totals[row.endpoint] = item; return totals; }, {})).sort((a, b) => b.total / b.count - a.total / a.count);
  return <><AdminHeader eyebrow="Performance" title="Application performance" description="API reliability, endpoint latency, browser Core Web Vitals, route performance, and device/browser issue context."><RangeLinks current={days} /></AdminHeader><div className={styles.metricGrid}><MetricCard label="API requests" value={api.length} /><MetricCard label="API success" value={`${api.length ? Math.round((api.length - failures) / api.length * 100) : 0}%`} tone={failures ? "warning" : "good"} /><MetricCard label="Average API latency" value={formatDuration(apiLatency)} /><MetricCard label="Web vital samples" value={web.length} /><MetricCard label="Poor web vitals" value={poorWeb} tone={poorWeb ? "warning" : "good"} /><MetricCard label="Tracked endpoints" value={endpoints.length} /></div><AdminPanel title="Endpoint performance"><AdminTable><thead><tr><th>Endpoint</th><th>Requests</th><th>Failures</th><th>Success</th><th>Average</th><th>Slowest</th></tr></thead><tbody>{endpoints.map((endpoint) => <tr key={endpoint.endpoint}><td><code>{endpoint.endpoint}</code></td><td>{endpoint.count}</td><td>{endpoint.failures}</td><td>{Math.round((endpoint.count - endpoint.failures) / endpoint.count * 100)}%</td><td>{formatDuration(endpoint.total / endpoint.count)}</td><td>{formatDuration(endpoint.max)}</td></tr>)}</tbody></AdminTable></AdminPanel><AdminPanel title="Web performance samples">{web.length ? <AdminTable><thead><tr><th>Time</th><th>Metric</th><th>Value</th><th>Rating</th><th>Route</th><th>Device</th><th>Browser / OS</th></tr></thead><tbody>{web.map((row) => <tr key={row.id}><td>{formatDate(row.created_at)}</td><td>{row.metric_name}</td><td>{row.metric_name === "CLS" ? Number(row.value).toFixed(3) : formatDuration(row.value)}</td><td><StatusBadge value={row.rating} /></td><td>{row.route || "—"}</td><td>{row.device_type || "—"}</td><td>{row.browser || "—"}<br /><small>{row.operating_system || ""}</small></td></tr>)}</tbody></AdminTable> : <EmptyAdminState />}</AdminPanel></>;
}