import type { Metadata } from "next";
import { AdminHeader, AdminPanel, AdminTable, EmptyAdminState, MetricCard, RangeLinks, StatusBadge, formatDate, formatMoney } from "@/components/admin/admin-ui";
import { requireAdmin } from "@/lib/admin/auth";
import { adminDateRange, getAdminRevenue, getAdminUsers } from "@/lib/admin/data";
import { recordAdminAudit } from "@/lib/telemetry/server";
import styles from "../admin.module.css";

export const metadata: Metadata = { title: "Revenue" };

export default async function AdminRevenuePage({ searchParams }: { searchParams: Promise<{ days?: string }> }) {
  const admin = await requireAdmin(); const { days } = adminDateRange((await searchParams).days); const [{ events, subscriptions, activeSubscriptions, mrrCents }, users] = await Promise.all([getAdminRevenue(days), getAdminUsers()]);
  await recordAdminAudit({ adminUserId: admin.id, action: "admin_page_viewed", targetType: "page", targetId: "revenue", metadata: { days } });
  const paidUsers = users.filter((user) => user.plan !== "free").length; const failedPayments = events.filter((event) => event.event_name === "invoice_failed").length; const canceled = subscriptions.filter((subscription) => subscription.status === "canceled").length; const revenue = events.filter((event) => event.event_name === "invoice_paid" && event.success).reduce((sum, event) => sum + Number(event.amount_cents || 0), 0);
  return <><AdminHeader eyebrow="Business operations" title="Revenue and subscriptions" description="MRR, recognized payments, conversion, churn indicators, plan distribution, and Stripe webhook outcomes."><RangeLinks current={days} /></AdminHeader><div className={styles.metricGrid}><MetricCard label="MRR" value={formatMoney(mrrCents)} tone="good" /><MetricCard label="Revenue in range" value={formatMoney(revenue)} /><MetricCard label="Paid users" value={paidUsers} detail={`${users.length - paidUsers} free`} /><MetricCard label="Active subscriptions" value={activeSubscriptions} /><MetricCard label="Canceled" value={canceled} tone={canceled ? "warning" : "default"} /><MetricCard label="Failed payments" value={failedPayments} tone={failedPayments ? "danger" : "good"} /></div><div className={styles.dashboardGrid}><AdminPanel title="Plan distribution"><AdminTable><thead><tr><th>Plan</th><th>Users</th></tr></thead><tbody>{["free", "starter", "pro", "max"].map((plan) => <tr key={plan}><td><StatusBadge value={plan} /></td><td>{users.filter((user) => user.plan === plan).length}</td></tr>)}</tbody></AdminTable></AdminPanel><AdminPanel title="Subscription state"><AdminTable><thead><tr><th>Status</th><th>Count</th></tr></thead><tbody>{Array.from(new Set(subscriptions.map((row) => row.status))).map((status) => <tr key={status}><td><StatusBadge value={status} /></td><td>{subscriptions.filter((row) => row.status === status).length}</td></tr>)}</tbody></AdminTable></AdminPanel></div><AdminPanel title="Stripe events" description="Provider event IDs are retained for deduplication; secrets and payment details are excluded.">{events.length ? <AdminTable><thead><tr><th>Time</th><th>Event</th><th>Success</th><th>User</th><th>Plan/status</th><th>Amount</th><th>Provider ID</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td>{formatDate(event.created_at)}</td><td>{event.event_name}</td><td><StatusBadge value={String(event.success)} /></td><td><code>{event.user_id ? String(event.user_id).slice(0, 8) : "—"}</code></td><td>{event.plan || "—"}<br /><small>{event.subscription_status || ""}</small></td><td>{event.amount_cents ? formatMoney(event.amount_cents) : "—"}</td><td><code>{event.provider_event_id ? String(event.provider_event_id).slice(0, 18) : "—"}</code></td></tr>)}</tbody></AdminTable> : <EmptyAdminState />}</AdminPanel></>;
}