import type { Metadata } from "next";
import { Search } from "lucide-react";
import { AdminHeader, AdminPanel, AdminTable, EmptyAdminState, MetricCard, PrivacyNotice, RangeLinks, StatusBadge, formatDate, formatDuration } from "@/components/admin/admin-ui";
import { requireAdmin } from "@/lib/admin/auth";
import { adminDateRange, getAdminFactChecks } from "@/lib/admin/data";
import { recordAdminAudit } from "@/lib/telemetry/server";
import styles from "../admin.module.css";

export const metadata: Metadata = { title: "Fact checks" };

export default async function AdminFactChecksPage({ searchParams }: { searchParams: Promise<{ days?: string; status?: string; inputType?: string; category?: string; user?: string }> }) {
  const admin = await requireAdmin(); const filters = await searchParams; const { days } = adminDateRange(filters.days); const checks = await getAdminFactChecks(days, filters);
  await recordAdminAudit({ adminUserId: admin.id, action: "admin_page_viewed", targetType: "page", targetId: "fact-checks", metadata: { days } });
  const completed = checks.filter((check) => check.status === "completed"); const failed = checks.filter((check) => check.status === "failed"); const latency = completed.length ? completed.reduce((sum, check) => sum + Number(check.duration_ms || 0), 0) / completed.length : 0; const inputCounts = checks.reduce<Record<string, number>>((total, check) => { total[check.input_type || "unknown"] = (total[check.input_type || "unknown"] || 0) + 1; return total; }, {}); const topInput = Object.entries(inputCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || "—";
  return <><AdminHeader eyebrow="Product funnel" title="Fact checks" description="Run metadata, stage failures, latency, categories, verdicts, and scores without raw user inputs."><RangeLinks current={days} /></AdminHeader><PrivacyNotice /><div className={styles.metricGrid}><MetricCard label="Runs" value={checks.length} /><MetricCard label="Completed" value={completed.length} tone="good" /><MetricCard label="Failed" value={failed.length} tone={failed.length ? "danger" : "good"} /><MetricCard label="Success rate" value={`${checks.length ? Math.round(completed.length / Math.max(1, completed.length + failed.length) * 100) : 0}%`} /><MetricCard label="Average latency" value={formatDuration(latency)} /><MetricCard label="Top input" value={topInput} /></div><form className={styles.filters}><input type="hidden" name="days" value={days} /><select className="select" name="status" defaultValue={filters.status || ""}><option value="">All statuses</option><option>started</option><option>completed</option><option>failed</option><option>rejected</option></select><select className="select" name="inputType" defaultValue={filters.inputType || ""}><option value="">All inputs</option><option>text</option><option>link</option><option>screenshot</option></select><input className="input" name="category" defaultValue={filters.category} placeholder="Exact category" /><input className="input" name="user" defaultValue={filters.user} placeholder="User UUID" /><button className="button"><Search size={16} /> Filter</button></form><AdminPanel title="Recent runs">{checks.length ? <AdminTable><thead><tr><th>Created</th><th>Status/stage</th><th>User</th><th>Input</th><th>Category</th><th>Verdict</th><th>Scores</th><th>Latency</th><th>Error</th></tr></thead><tbody>{checks.map((check) => <tr key={check.id}><td>{formatDate(check.created_at)}</td><td><StatusBadge value={check.status} /><br /><small>{check.stage}</small></td><td><code>{check.user_id ? String(check.user_id).slice(0, 8) : "anonymous"}</code></td><td>{check.input_type || "—"}</td><td>{check.category || "—"}</td><td><StatusBadge value={check.verdict} /></td><td>{check.truth_score ?? "—"} / {check.confidence_score ?? "—"}</td><td>{formatDuration(check.duration_ms)}</td><td>{check.error_code || "—"}<br /><small>{check.error_reason || ""}</small></td></tr>)}</tbody></AdminTable> : <EmptyAdminState />}</AdminPanel></>;
}